# Generated by Django 4.0.6 on 2022-09-05 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_aramcode_customer_orderinfo_orderdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='fruit_idx',
            new_name='fruitlist',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='order_info_idx',
            new_name='orderinfo',
        ),
    ]
