# Generated by Django 4.0.6 on 2022-09-05 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_customer_id_alter_customer_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='author',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='author',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='fruitlist',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='orderinfo',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='author',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='shipping_type',
        ),
        migrations.DeleteModel(
            name='AramCode',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
        migrations.DeleteModel(
            name='OrderInfo',
        ),
    ]
